title: SegMetric
description: Tools for converting, segmenting, cropping, and measuring images.
theme: minima

header_pages:
  - tag.md
  - set.md
  - scale.md
  - prepare.md
  - mask.md
  - segment.md
  - landmark.md
  - measure.md

minima:
  skin: auto

github_username: Casey-Lambert
repository: Casey-Lambert/segmetric

markdown: kramdown
